spring:
  application:
    name: Obs

management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local
      "service.name": ${spring.application.name}
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

